export const studentData = {
  "SS3A": [
    {
      "name": "Olalekan Hubaidat Yetunde",
      "date_of_birth": "8/5/2009",
      "phone_number": "08068962457",
      "short_quote": "Believe in yourself and Be your best self and never give up on your dreams🌚🖤",
      "whatsapp_number": "08068962457",
      "facebook_name": "",
      "instagram": "theonlymidey",
      "twitter": "",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Adekanbi Abdul basit opeyemi",
      "date_of_birth": "6/1/2008",
      "phone_number": "09120412719",
      "short_quote": "An architect\nAffiliate marketer\nAn entrepreneur and a crypto enthusiasts",
      "whatsapp_number": "09120412719",
      "facebook_name": "https://www.facebook.com/abdul.basit.opeyemi.184191",
      "instagram": "https://www.instagram.com/coach_abdulbasit1?igsh=MXZ0enV0ZjVsZ2x4OA==",
      "twitter": "Earn_with_Abdul basit😎💸",
      "snapchat": "https://www.snapchat.com/add/modinatkehind25?share_id=WfwHj1cpL-o&locale=en-US",
      "tiktok": "tiktok.com/@abasisco48",
      "others": "https://www.linkedin.com/in/abdul-basit-opeyemi-868765356?ut"
    },
    {
      "name": "TITILAYO Joseph",
      "date_of_birth": "11/17/2008",
      "phone_number": "08144773114",
      "short_quote": "Our future is Bright",
      "whatsapp_number": "08144773114",
      "facebook_name": "",
      "instagram": "",
      "twitter": "",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "FASHOLA ASHIYYA",
      "date_of_birth": "8/18/2008",
      "phone_number": "09047844045",
      "short_quote": "Together we navigated, together we conquered. Cheers to new beginnings\nNew chapter, new story. Let's make it legendary!",
      "whatsapp_number": "09047844045",
      "facebook_name": "Titilope Fashola",
      "instagram": "Titilope Fashola",
      "twitter": "Omotoyosi Fashola",
      "snapchat": "Black heart",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Adedeji Adejoke Esther",
      "date_of_birth": "1/11/2009",
      "phone_number": "08161534171",
      "short_quote": "Never give up on yourself",
      "whatsapp_number": "08161534171",
      "facebook_name": "None",
      "instagram": "Adedeji Adejoke",
      "twitter": "None",
      "snapchat": "https://www.snapchat.com/add/adejoke_esthe25?share_id=tUnN897waOM&locale=en-NG",
      "tiktok": "https://vm.tiktok.com/ZMSVsU7jf/",
      "others": ""
    },
    {
      "name": "Olawole Deborah",
      "date_of_birth": "6/22/2009",
      "phone_number": "07075911487",
      "short_quote": "Life is full of ups and downs",
      "whatsapp_number": "07075011487",
      "facebook_name": "Olawole Deborah",
      "instagram": "Olawole Deborah",
      "twitter": "",
      "snapchat": "olawoledeborah55",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Omotoyosi Elizabeth Oluwasemilore",
      "date_of_birth": "1/21/2010",
      "phone_number": "07071523877",
      "short_quote": "The journey ahead is bright. Let's not forget all the memories and laughter shared",
      "whatsapp_number": "07071523877",
      "facebook_name": "Horluwa Semmyloore",
      "instagram": "Elizabeth Oluwasemilore",
      "twitter": "Horluwasemmyloore",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Uyebo chinemerem gift",
      "date_of_birth": "3/27/2009",
      "phone_number": "07060532169",
      "short_quote": "Never give up😊",
      "whatsapp_number": "07060532169",
      "facebook_name": "Irreplaceable gift",
      "instagram": "Uyebo gift",
      "twitter": "Uyebo gift",
      "snapchat": "Gift",
      "tiktok": "Raregift 3",
      "others": "None"
    },
    {
      "name": "Akanmu Joy Madamidaoluwa",
      "date_of_birth": "6/1/2009",
      "phone_number": "09055088662",
      "short_quote": "Respect and honor open door to greatness",
      "whatsapp_number": "09055088662",
      "facebook_name": "Akanmu Joy",
      "instagram": "None",
      "twitter": "Akanmu Joy",
      "snapchat": "Joycebabe12345",
      "tiktok": "Follow me on my social Media platform",
      "others": ""
    }
  ],
  "SS3B": [
    {
      "name": "OLATUNDE DAVID OLUWAFIKUNAYOMI",
      "date_of_birth": "11/30/2008",
      "phone_number": "08025549442",
      "short_quote": "Feel free",
      "whatsapp_number": "+2348025549442",
      "facebook_name": "Unavailable",
      "instagram": "Unavailable",
      "twitter": "Unavailable",
      "snapchat": "Unavailable",
      "tiktok": "feekay_1964",
      "others": "UNAVAILABLE"
    },
    {
      "name": "Popoola Ogomide Joseph",
      "date_of_birth": "2/1/2010",
      "phone_number": "07030156072",
      "short_quote": "The next time we meet, I'll be better than I was now",
      "whatsapp_number": "07030156072",
      "facebook_name": "Mäy He Ädd",
      "instagram": "Nil (but if I were to have, it would be Mäy He Ädd)",
      "twitter": "Nil (but if I were to have, it would be Mäy He Ädd)",
      "snapchat": "May He Add",
      "tiktok": "Nil (but if I were to have, it would be Mäy He Ädd)",
      "others": "Nil"
    },
    {
      "name": "Adesina hanif",
      "date_of_birth": "8/4/2009",
      "phone_number": "08108090849",
      "short_quote": "Don't let others stop you from doing what you love those who matter won't mind, and those who mind don't matter.",
      "whatsapp_number": "08108090849",
      "facebook_name": "Hanif adesina",
      "instagram": "@hanifadesina",
      "twitter": "hanifadesina_6",
      "snapchat": "@adesinahanif761",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Hassan Husnah olamide",
      "date_of_birth": "10/10/2009",
      "phone_number": "08082574383",
      "short_quote": "Your journey is just beginning, the best stories are still waiting to be written",
      "whatsapp_number": "08082574383",
      "facebook_name": "Hassan Husnah",
      "instagram": "Hassan Husnah",
      "twitter": "",
      "snapchat": "Midnight sparkle ✨",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Asho Blessing Gladys",
      "date_of_birth": "9/8/2008",
      "phone_number": "07086339470",
      "short_quote": "Don't do anything to please anyone if it ain't pleasing you then don't do it",
      "whatsapp_number": "07086339470",
      "facebook_name": "Osereme Blessing",
      "instagram": "Osereme Blessing",
      "twitter": "Blessing Asho",
      "snapchat": "__osereme7",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Awe Elijah Olaniyi",
      "date_of_birth": "12/23/2008",
      "phone_number": "09131740614",
      "short_quote": "We survived\"pens up\" and \"Tear a sheet of paper\" now we fit survive anything",
      "whatsapp_number": "09131740614",
      "facebook_name": "Awe Elijah",
      "instagram": "Awe Elijah",
      "twitter": "Awe Elijah",
      "snapchat": "Golden Graphix",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Salami Thesirah Oyeladun",
      "date_of_birth": "9/3/2007",
      "phone_number": "08100845715",
      "short_quote": "Raise your self respect so high that loosing people feels like a blessing not a loss",
      "whatsapp_number": "08100845715",
      "facebook_name": "Abdulsalam Thesirah",
      "instagram": "Tessy olamide",
      "twitter": "None",
      "snapchat": "Radiant resa",
      "tiktok": "Radiant-Resa-04",
      "others": "None"
    },
    {
      "name": "Mustapha Fathia Eniola",
      "date_of_birth": "8/24/2008",
      "phone_number": "07082239170",
      "short_quote": "The future belongs to those who believe in the beauty of their dreams",
      "whatsapp_number": "07088871051",
      "facebook_name": "",
      "instagram": "",
      "twitter": "",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "AKINDELE ERIOLUWA DORCAS",
      "date_of_birth": "5/30/2010",
      "phone_number": "09113694042",
      "short_quote": "I will really miss all those who have made VETLAND memories a memorable one for me.😗😊😊\nI wish us all success.🥰",
      "whatsapp_number": "09113694042",
      "facebook_name": "Akindele Erioluwa",
      "instagram": "Erioluwa Akindele",
      "twitter": "damsel🥰darcy🥰",
      "snapchat": "damsel darcy",
      "tiktok": "",
      "others": ""
    }
  ],
  "SS3c": [
    {
      "name": "OKUNIYI ABDULMALIK ADEWALE",
      "date_of_birth": "2/23/2009",
      "phone_number": "07010980765",
      "short_quote": "Be kind",
      "whatsapp_number": "07010980765",
      "facebook_name": "Not on fb",
      "instagram": "Abdulmalik Okuniyi",
      "twitter": "https://x.com/O3311772459336?t=sS5Yt4-EnIyd6t6rVH5B1A&s=09",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Ogunleye Mary Odunayo",
      "date_of_birth": "12/16/2009",
      "phone_number": "09023427380",
      "short_quote": "The sky is just my starting point as long as I am focused and not distracted",
      "whatsapp_number": "09023427380 or 08034999911",
      "facebook_name": "Priscilla Ogunleye",
      "instagram": "Priscilla Ogunleye",
      "twitter": "Ogunleye Mary",
      "snapchat": "pwetty princess 😛😌🤭🥰😎❤😁",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "ADEGOLU FAITH AYOMIDE",
      "date_of_birth": "1/20/2009",
      "phone_number": "07083049348",
      "short_quote": "To live a creative life, we must lose our fear of being wrong",
      "whatsapp_number": "07083049348",
      "facebook_name": "😍Ade Ola😍",
      "instagram": "Hardeyhorlah",
      "twitter": "",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Tiwo Oluwasemilore Divine",
      "date_of_birth": "6/4/2010",
      "phone_number": "09069183428",
      "short_quote": "Education is the key to success",
      "whatsapp_number": "09069183428",
      "facebook_name": "Tiwo Devine",
      "instagram": "NIL",
      "twitter": "NIL",
      "snapchat": "NIL",
      "tiktok": "NIL",
      "others": "NIL"
    },
    {
      "name": "Nosarume Covenant",
      "date_of_birth": "5/3/2009",
      "phone_number": "07078776596",
      "short_quote": "Believe you can, and you're halfway there",
      "whatsapp_number": "07078776596",
      "facebook_name": "None",
      "instagram": "simpfor_covy",
      "twitter": "None",
      "snapchat": "fw.zoeyy",
      "tiktok": "simpfor_covy",
      "others": ""
    },
    {
      "name": "IBE WISDOM CHIDIEBERE",
      "date_of_birth": "5/6/2008",
      "phone_number": "09028815451",
      "short_quote": "If you're brave enough to say goodbye life would reward u with hello",
      "whatsapp_number": "09028815451",
      "facebook_name": "Whîzzy boi",
      "instagram": "Whîzzy bhøï001",
      "twitter": "",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Adegbola Marvellous",
      "date_of_birth": "6/3/2009",
      "phone_number": "08029423279",
      "short_quote": "Wishing y'all the best😘",
      "whatsapp_number": "08029423279",
      "facebook_name": "",
      "instagram": "",
      "twitter": "",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Hephzy Marvell",
      "date_of_birth": "7/27/2025",
      "phone_number": "09134248014",
      "short_quote": "God carried us through what we thought we couldn't survive—this is grace in motion.",
      "whatsapp_number": "09134248014",
      "facebook_name": "Hephzy Marvell",
      "instagram": "Hephzy Marvell",
      "twitter": "Hephzy Marvell",
      "snapchat": "Hephzy Marvell",
      "tiktok": "hephzy 72",
      "others": ""
    }
  ],
  "SS3D": [
    {
      "name": "OLADEJO ADESEWA OLOLADE",
      "date_of_birth": "10/29/2009",
      "phone_number": "09075126418",
      "short_quote": "The true sign of intelligence is not knowledge but imagination, as I finish secondary school I will always be at the top.",
      "whatsapp_number": "09075126418",
      "facebook_name": "Adesewa ololade",
      "instagram": "Adewale Oladejo",
      "twitter": "Adejoke",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Olatunde Ameerah Toluwanimi",
      "date_of_birth": "4/10/2009",
      "phone_number": "09118357335",
      "short_quote": "Every disappointment is a blessing in disguise.",
      "whatsapp_number": "09118357335",
      "facebook_name": "None",
      "instagram": "PEAMOATA",
      "twitter": "None",
      "snapchat": "PEAMOATA",
      "tiktok": "NEEMEEH",
      "others": "TELEGRAM: Olatunde Ameerah Toluwanimi"
    }
  ],
  "SS3E": [
    {
      "name": "Solomon Goodness",
      "date_of_birth": "7/14/2008",
      "phone_number": "08148258814",
      "short_quote": "Stay string, pursue your dreams don't give up",
      "whatsapp_number": "08148258814",
      "facebook_name": "Regina rules",
      "instagram": "Null",
      "twitter": "Null",
      "snapchat": "Charityedet",
      "tiktok": "Edetqueen",
      "others": "Jaye lo"
    },
    {
      "name": "AGBOTA IREDIA PEACE",
      "date_of_birth": "6/16/2008",
      "phone_number": "902,928,394,509,153,000,000",
      "short_quote": "Live your life to the fullest with God,and don't be to carried away with the things of this world.",
      "whatsapp_number": "09029283945",
      "facebook_name": "AGBOTA IREDIA",
      "instagram": "AGBOTA IREDIA",
      "twitter": "Non",
      "snapchat": "AGBOTA IREDIA",
      "tiktok": "@agbotairedia",
      "others": "Alpha papa"
    },
    {
      "name": "YUSUF ADAM AYOMIDE",
      "date_of_birth": "9/19/2008",
      "phone_number": "+2348036148536",
      "short_quote": "MAKE HAY WHILE THE SUN SHINES",
      "whatsapp_number": "+2348036148536",
      "facebook_name": "Yusuf Adam",
      "instagram": "Yusuf Adam",
      "twitter": "Nil",
      "snapchat": "Nil",
      "tiktok": "Nil",
      "others": "Nil"
    },
    {
      "name": "OZOJIE AMALACHUKWU BENEDICTA",
      "date_of_birth": "2/27/2009",
      "phone_number": "08169520096",
      "short_quote": "\"The future belongs to those who believe in the beauty of their dreams.\"",
      "whatsapp_number": "08169520096",
      "facebook_name": "Bene Dicta",
      "instagram": "Ama Ozojie",
      "twitter": "Simply_Benedicta",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Mosaku david",
      "date_of_birth": "4/22/2009",
      "phone_number": "09128688361",
      "short_quote": "Greater height",
      "whatsapp_number": "09128688361",
      "facebook_name": "David moore",
      "instagram": "David moore",
      "twitter": "David moore",
      "snapchat": "Oluwatosin01.com",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "ADEBAYO MUHEEZ AYINDE",
      "date_of_birth": "5/28/2008",
      "phone_number": "09066203219",
      "short_quote": "Believe in yourself, work hard, and never give up on your dreams. Your education is the foundation upon which your future is built.",
      "whatsapp_number": "09066203219",
      "facebook_name": "",
      "instagram": "https://www.instagram.com/muhee_z002?igsh=NnV0NWFzZHk1b3Fi",
      "twitter": "",
      "snapchat": "Add me on Snapchat! Username: mu_heez001 https://www.snapchat.com/add/mu_heez001?share_id=dyPan7eYsyo&",
      "tiktok": "https://www.tiktok.com/@muheez09?_t=ZM-8yES6pVfvM5&_r=1",
      "others": "Add me on Snapchat! Username: mu_heez001 https://www.snap"
    },
    {
      "name": "Nobiu Abdulgafar abiodun",
      "date_of_birth": "12/6/2008",
      "phone_number": "9168564752",
      "short_quote": "Anything you like doing worth doing",
      "whatsapp_number": "09168564752",
      "facebook_name": "ABIODUN DC",
      "instagram": "Abiodun_Dc1",
      "twitter": "Abiodun_Dc",
      "snapchat": "",
      "tiktok": "",
      "others": ""
    },
    {
      "name": "Deybeesi",
      "date_of_birth": "7/6/2010",
      "phone_number": "09137946797",
      "short_quote": "I have nothing to say",
      "whatsapp_number": "09137946797",
      "facebook_name": "Olatundun The Ceo 💕❤",
      "instagram": "I don't have",
      "twitter": "I don't have",
      "snapchat": "Olasunbo",
      "tiktok": "@ deybeesi10",
      "others": ""
    },
    {
      "name": "Adeoye Glory Oluwadamilola",
      "date_of_birth": "8/11/2009",
      "phone_number": "08107683032",
      "short_quote": "No matter what happens keep on fighting",
      "whatsapp_number": "08107683032",
      "facebook_name": "Oluwadarhmy Adeoye",
      "instagram": "Zoey_darhmy",
      "twitter": "Zoey_darhmy",
      "snapchat": "Zhoey_darhmy09",
      "tiktok": "Zoey_darhmy",
      "others": "Zoey_darhmy"
    },
    {
      "name": "Akeresola success peace",
      "date_of_birth": "6/6/2009",
      "phone_number": "09015777374",
      "short_quote": "I'm grateful",
      "whatsapp_number": "09015777374",
      "facebook_name": "Akeresola pizco",
      "instagram": "Akeresola pizco",
      "twitter": "Akeresola success",
      "snapchat": "Akeresola success",
      "tiktok": "Pizco 6",
      "others": "Akeresola success"
    },
    {
      "name": "Dada Oluwasholafunmi Hephzibah",
      "date_of_birth": "1/4/2009",
      "phone_number": "08131095615",
      "short_quote": "The future belongs to those who believe in new chapters and new beginnings.",
      "whatsapp_number": "08131095615",
      "facebook_name": "None",
      "instagram": "None",
      "twitter": "None",
      "snapchat": "Sholly",
      "tiktok": "Hephzibah 0104",
      "others": "None."
    }
  ]

}
