export const studentData = [

    
      {
        "name": "Solomon Goodness",
        "class": "SS3E",
        "date_of_birth": "7/14/2008",
        "phone_number": "08148258814",
        "short_quote": "Stay string, pursue your dreams don't give up",
        "whatsapp_number": "08148258814",
        "facebook_name": "Regina rules",
        "instagram": "Null",
        "twitter": "Null",
        "snapchat": "Charityedet",
        "tiktok": "Edetqueen",
        "others": "Jaye lo"
      },
      {
        "name": "AGBOTA IREDIA PEACE",
        "class": "SS3E",
        "date_of_birth": "6/16/2008",
        "phone_number": "902,928,394,509,153,000,000",
        "short_quote": "Live your life to the fullest with God,and don't be to carried away with the things of this world.",
        "whatsapp_number": "09029283945",
        "facebook_name": "AGBOTA IREDIA",
        "instagram": "AGBOTA IREDIA",
        "twitter": "Non",
        "snapchat": "AGBOTA IREDIA",
        "tiktok": "@agbotairedia",
        "others": "Alpha papa"
      },
      {
        "name": "OKUNIYI ABDULMALIK ADEWALE",
        "class": "SS3C",
        "date_of_birth": "2/23/2009",
        "phone_number": "07010980765",
        "short_quote": "Be kind",
        "whatsapp_number": "07010980765",
        "facebook_name": "Not on fb",
        "instagram": "Abdulmalik Okuniyi",
        "twitter": "https://x.com/O3311772459336?t=sS5Yt4-EnIyd6t6rVH5B1A&s=09",
        "snapchat": null,
        "tiktok": null,
        "others": null
      },
      {
        "name": "OLATUNDE DAVID OLUWAFIKUNAYOMI",
        "class": "SS3B",
        "date_of_birth": "11/30/2008",
        "phone_number": "08025549442",
        "short_quote": "Feel free",
        "whatsapp_number": "+2348025549442",
        "facebook_name": "Unavailable",
        "instagram": "Unavailable",
        "twitter": "Unavailable",
        "snapchat": "Unavailable",
        "tiktok": "feekay_1964",
        "others": "UNAVAILABLE"
      },
      {
        "name": "Popoola Ogomide Joseph",
        "class": "SS3B",
        "date_of_birth": "2/1/2010",
        "phone_number": "07030156072",
        "short_quote": "The next time we meet, I'll be better than I was now",
        "whatsapp_number": "07030156072",
        "facebook_name": "Mäy He Ädd",
        "instagram": "Nil (but if I were to have, it would be Mäy He Ädd)",
        "twitter": "Nil (but if I were to have, it would be Mäy He Ädd)",
        "snapchat": "May He Add",
        "tiktok": "Nil (but if I were to have, it would be Mäy He Ädd)",
        "others": "Nil"
      },
      {
        "name": "Adesina hanif",
        "class": "SS3B",
        "date_of_birth": "8/4/2009",
        "phone_number": "08108090849",
        "short_quote": "Don't let others stop you from doing what you love those who matter won't mind, and those who mind don't matter.",
        "whatsapp_number": "08108090849",
        "facebook_name": "Hanif adesina",
        "instagram": "@hanifadesina",
        "twitter": "hanifadesina_6",
        "snapchat": "@adesinahanif761",
        "tiktok": null,
        "others": null
      },
      {
        "name": "YUSUF ADAM AYOMIDE",
        "class": "SS3E",
        "date_of_birth": "9/19/2008",
        "phone_number": "+2348036148536",
        "short_quote": "MAKE HAY WHILE THE SUN SHINES",
        "whatsapp_number": "+2348036148536",
        "facebook_name": "Yusuf Adam",
        "instagram": "Yusuf Adam",
        "twitter": "Nil",
        "snapchat": "Nil",
        "tiktok": "Nil",
        "others": "Nil"
      },
      {
        "name": "OLADEJO ADESEWA OLOLADE",
        "class": "SS3D",
        "date_of_birth": "10/29/2009",
        "phone_number": "09075126418",
        "short_quote": "The true sign of intelligence is not knowledge but imagination,as I finish secondary school I will always be at the top.",
        "whatsapp_number": "09075126418",
        "facebook_name": "Adesewa ololade",
        "instagram": "Adewale Oladejo",
        "twitter": null,
        "snapchat": null,
        "tiktok": "Adejoke",
        "others": null
      },
      {
        "name": "Ogunleye Mary Odunayo",
        "class": "SS3C",
        "date_of_birth": "12/16/2009",
        "phone_number": "09023427380",
        "short_quote": "The sky is just my starting point as long as I am focused and not distracted",
        "whatsapp_number": "09023427380 or 08034999911",
        "facebook_name": "Priscilla Ogunleye",
        "instagram": "Priscilla Ogunleye",
        "twitter": "Ogunleye Mary",
        "snapchat": "pwetty princess 😛😌🤭🥰😎❤😁",
        "tiktok": null,
        "others": null
      },
      {
        "name": "Olalekan Hubaidat Yetunde",
        "class": "SS3A",
        "date_of_birth": "8/5/2009",
        "phone_number": "08068962457",
        "short_quote": "Believe in yourself and Be your best self and never give up on your dreams🌚🖤",
        "whatsapp_number": "08068962457",
        "facebook_name": "theonlymidey",
        "instagram": null,
        "twitter": null,
        "snapchat": null,
        "tiktok": null,
        "others": null
      }
    
  
]